name: ai_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  # google_generative_ai: ^0.4.7
  http: ^1.6.0
  path_provider: ^2.0.7
  path_provider_tizen: ^2.2.1
  grpc: ^5.1.0
  protobuf: ^6.0.0
  fixnum: ^1.1.0
  path: ^1.8.0
  tizen_app_control: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  protoc_plugin: ^25.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bixby.png

