syntax = "proto3";
package carbon.v1;

service ConfigService {
  rpc GetConfig(GetConfigRequest) returns (GetConfigResponse);
  rpc SetConfig(SetConfigRequest) returns (SetConfigResponse);
}

message GetConfigRequest {}

message GetConfigResponse {
  string yaml           = 1;
  bool   ready          = 2;
  string hint           = 3;
}

message SetConfigRequest {
  string yaml = 1;
}

message SetConfigResponse {
  bool   success         = 1;
  string message         = 2;
  bool   restart_success = 3;
}
